version: "3"

services:
  default-answer:
      build:
        context: .
        dockerfile: Dockerfile.app
      volumes:
        - ./app:/app
      depends_on:
        - db
      environment:
        - DEBUG=defaultanswer:info,defaultanswer:error
  db:
      build:
        context: .
        dockerfile: Dockerfile.db
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=nemanja
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
