version: "3"

services:
  default-answer:
      build:
        context: .
        dockerfile: Dockerfile.app
      volumes:
        - ./app:/app
        - /app/node_modules
      links:
        - db
      depends_on:
        - db
      environment:
        - DEBUG=default-answer-server:info,default-answer-server:error
  db:
      build:
        context: .
        dockerfile: Dockerfile.db
