version: "3"

services:
  default-answer:
      build:
        context: .
        dockerfile: Dockerfile.app
      links:
        - db
      depends_on:
        - db
      environment:
        - DEBUG=default-answer-client:info,default-answer-server:error
  db:
      build:
        context: .
        dockerfile: Dockerfile.db
      environment:
        - MYSQL_USER=nemanja
        - MYSQL_DATABASE=defaultanswerdb
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=default_root_pass
